/**
 * Unit Catalog — backed by the on-disk inventory.
 * ────────────────────────────────────────────────────────────────────────────
 * Single source of truth: `src/data/partInventory.json`, generated by
 * `scripts/inspect-models.mjs` from the actual glTF files. Re-run that
 * script whenever the GLBs change; this module reads its output at compile
 * time.
 *
 * Discovery (from real GLB inspection):
 *   - Each race's `infantry.gltf` and `cavalry.gltf` is a SINGLE assembled
 *     model containing every body/head/arm/leg/shoulderpad variant AND
 *     every weapon/shield/prop, each as a separately named mesh. Customizing
 *     a unit is therefore mesh-visibility toggling, not file swapping.
 *   - Attach sockets are named transforms parented under hand/spine bones
 *     (see `ATTACH_POINTS`). Use these — never parent props directly to a
 *     bone — they encode the artist-authored grip orientation.
 *   - Infantry skeleton: 18 Bip001 bones. Cavalry skeleton: 40 bones
 *     (rider biped + mount rig fused). Siege rigs are bespoke (10–14 bones)
 *     and are NOT Mixamo-compatible.
 */

import inventoryJson from './partInventory.json';
import {
  GRUDGE_RACE_IDS,
  inventoryKeyFor,
  type GrudgeRaceId,
  type LegacyFactionId,
} from './grudgeRaces';

/** Canonical GRUDGE 6 race id (matches character-viewer). */
export type FactionId = GrudgeRaceId;
export type ModelKind = 'infantry' | 'cavalry' | 'siege';

/** Logical part slot from the build sheet. */
export type PartSlot =
  | 'head'
  | 'body'
  | 'arms'
  | 'legs'
  | 'shoulderpad'
  | 'weapon'
  | 'shield'
  | 'prop'
  | 'mount'
  | 'siege_engine'
  | 'unknown';

/** Weapon sub-category, used to choose attach point + animation set. */
export type WeaponKind =
  | 'sword' | 'axe' | 'blunt' | 'spear' | 'lance'
  | 'dagger' | 'staff' | 'bow' | 'shield'
  | 'wood' | 'bag' | 'quiver';

export interface InventoryPart {
  /** Mesh name as it appears in the glTF (e.g. `WK_weapon_sword_A`). */
  name: string;
  slot: PartSlot;
  kind?: WeaponKind;
  /** Transform node the prop's mesh is parented to in-engine, e.g.
   *  `R_hand_container`. `null` means it's a body part skinned to the rig. */
  attachPoint?: string | null;
}

export interface InventoryModel {
  meshCount: number;
  meshNames: string[];
  /** Bone-name list (= `Bip001 *` joints + mount/siege joints). */
  boneNames: string[];
  /** Non-bone Transform nodes used as weapon/prop sockets. */
  attachPoints: string[];
  parts: InventoryPart[];
}

export interface RaceInventory {
  infantry?: InventoryModel;
  cavalry?: InventoryModel;
  siege?: InventoryModel;
}

interface Inventory {
  generatedAt: string;
  races: Record<LegacyFactionId, RaceInventory>;
}

export const INVENTORY = inventoryJson as Inventory;

// ─────────────────────────────────────────────────────────────────────────────
// Authoritative attach-point map (extracted from real model inspection).
// Use these constants everywhere props are parented; do NOT hard-code raw
// bone names like `Bip001 R Hand` — the containers carry the artist-authored
// orientation that makes the grip look right.
// ─────────────────────────────────────────────────────────────────────────────

export const ATTACH_POINTS = {
  /** Main weapon hand (sword/axe/hammer/spear/lance/dagger/staff). */
  R_HAND: 'R_hand_container',
  /** Off-hand for bows (archer draws right, holds left). */
  L_HAND: 'L_hand_container',
  /** Dedicated shield socket — distinct from L_hand_container. */
  L_SHIELD: 'L_shield_container',
  /** Worker carrying wood logs. */
  WOOD: 'Bone_wood',
  /** Worker carrying a goods bag. */
  BAG: 'Bone_bag',
  /** Quiver of arrows on the back. */
  QUIVER: 'Quiver_container',
  /** Cavalry mount root — present on `cavalry.gltf` only. */
  MOUNT: 'Bone_Mount',
} as const;

/** What socket a weapon kind should snap to. */
export const ATTACH_FOR_WEAPON: Record<WeaponKind, string> = {
  sword:   ATTACH_POINTS.R_HAND,
  axe:     ATTACH_POINTS.R_HAND,
  blunt:   ATTACH_POINTS.R_HAND,
  spear:   ATTACH_POINTS.R_HAND,
  lance:   ATTACH_POINTS.R_HAND,
  dagger:  ATTACH_POINTS.R_HAND,
  staff:   ATTACH_POINTS.R_HAND,
  bow:     ATTACH_POINTS.L_HAND,
  shield:  ATTACH_POINTS.L_SHIELD,
  wood:    ATTACH_POINTS.WOOD,
  bag:     ATTACH_POINTS.BAG,
  quiver:  ATTACH_POINTS.QUIVER,
};

// ─────────────────────────────────────────────────────────────────────────────
// Build-sheet unit roster (infantry, spearman, archer, mage, worker,
// cavalry × {sword,spear,archer,mage}, siege). Each unit is a recipe:
//   "pick a body + head + arms + legs + (shoulderpad) + (weapon kind) +
//    (shield) from the race's inventory."
// The actual mesh choices are deferred to runtime; this catalog only states
// which slots to fill and which weapon kind / animation set applies.
// ─────────────────────────────────────────────────────────────────────────────

export type UnitType =
  | 'infantry' | 'spearman' | 'archer' | 'mage' | 'worker'
  | 'cavalry' | 'cavalry_spear' | 'cavalry_archer' | 'cavalry_mage'
  | 'siege';

export type AnimationSetId =
  | 'infantry_sword_shield' | 'infantry_spear' | 'infantry_archer'
  | 'infantry_mage' | 'worker'
  | 'cavalry_sword_shield' | 'cavalry_spear' | 'cavalry_archer' | 'cavalry_mage'
  | 'siege_catapult' | 'siege_boltthrower';

export interface UnitRecipe {
  faction: FactionId;
  unitType: UnitType;
  modelKind: ModelKind;
  /** Which weapon kind this unit equips (drives `R_hand_container` mesh). */
  weaponKind: WeaponKind | null;
  /** True if the off-hand should hold a shield (`L_shield_container`). */
  hasShield: boolean;
  /** Mixamo animation-set tag — see `docs/MIXAMO_PROMPT.md` §2. */
  animationSet: AnimationSetId;
}

const FACTIONS: FactionId[] = GRUDGE_RACE_IDS;

function recipesFor(faction: FactionId): UnitRecipe[] {
  const inv = INVENTORY.races[inventoryKeyFor(faction)];
  const out: UnitRecipe[] = [
    { faction, unitType: 'infantry',       modelKind: 'infantry', weaponKind: 'sword', hasShield: true,  animationSet: 'infantry_sword_shield' },
    { faction, unitType: 'spearman',       modelKind: 'infantry', weaponKind: 'spear', hasShield: true,  animationSet: 'infantry_spear' },
    { faction, unitType: 'archer',         modelKind: 'infantry', weaponKind: 'bow',   hasShield: false, animationSet: 'infantry_archer' },
    { faction, unitType: 'mage',           modelKind: 'infantry', weaponKind: 'staff', hasShield: false, animationSet: 'infantry_mage' },
    { faction, unitType: 'worker',         modelKind: 'infantry', weaponKind: null,    hasShield: false, animationSet: 'worker' },
    { faction, unitType: 'cavalry',        modelKind: 'cavalry',  weaponKind: 'sword', hasShield: true,  animationSet: 'cavalry_sword_shield' },
    { faction, unitType: 'cavalry_spear',  modelKind: 'cavalry',  weaponKind: 'lance', hasShield: false, animationSet: 'cavalry_spear' },
    { faction, unitType: 'cavalry_archer', modelKind: 'cavalry',  weaponKind: 'bow',   hasShield: false, animationSet: 'cavalry_archer' },
    { faction, unitType: 'cavalry_mage',   modelKind: 'cavalry',  weaponKind: 'staff', hasShield: false, animationSet: 'cavalry_mage' },
  ];
  if (inv?.siege) {
    const isBolt = inv.siege.parts.some((p) => /boltthrower/i.test(p.name));
    out.push({
      faction, unitType: 'siege', modelKind: 'siege',
      weaponKind: null, hasShield: false,
      animationSet: isBolt ? 'siege_boltthrower' : 'siege_catapult',
    });
  }
  return out;
}

export const UNIT_RECIPES: UnitRecipe[] = FACTIONS.flatMap(recipesFor);

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

export function partsForFaction(faction: FactionId, kind: ModelKind, slot: PartSlot): InventoryPart[] {
  const model = INVENTORY.races[inventoryKeyFor(faction)]?.[kind];
  if (!model) return [];
  return model.parts.filter((p) => p.slot === slot);
}

export function weaponsForKind(faction: FactionId, kind: ModelKind, weaponKind: WeaponKind): InventoryPart[] {
  const model = INVENTORY.races[inventoryKeyFor(faction)]?.[kind];
  if (!model) return [];
  return model.parts.filter((p) => p.slot === 'weapon' && p.kind === weaponKind);
}

export function findRecipe(faction: FactionId, unitType: UnitType): UnitRecipe | undefined {
  return UNIT_RECIPES.find((u) => u.faction === faction && u.unitType === unitType);
}

/** Pick a default mesh (first match) to fill the recipe's weapon slot. */
export function defaultWeaponMeshFor(recipe: UnitRecipe): InventoryPart | null {
  if (!recipe.weaponKind) return null;
  return weaponsForKind(recipe.faction, recipe.modelKind, recipe.weaponKind)[0] ?? null;
}

export function defaultShieldMeshFor(recipe: UnitRecipe): InventoryPart | null {
  if (!recipe.hasShield) return null;
  return partsForFaction(recipe.faction, recipe.modelKind, 'shield')[0] ?? null;
}
